Updated handler to return response body and omit unecessary data
kineticdata/peripherals-utilities pull request #26
Opened 2022-04-11 15:45 UTC by Concord511

Mary- please review.

2022-04-11 16:01 UTC, itsMarydan reviewed
Everything looks good, just need to update the readme file, info.xml, and node.xml  these files need to reflect your changes to space_slug. They currently make references to space_slug.

2022-04-11 16:36 UTC, itsMarydan approved these changes

2022-04-12 15:13 UTC, jackboespflug commented
I've attached a diff that includes changes to some problems and/or clarity items I discovered while reviewing the code. I don't have an endpoint to test the changes however, so it would be a great to apply the patch `git apply per-267.patch.log` and then run the test harness on the handler.

[per-267.patch.log](https://github.com/kineticdata/peripherals-utilities/files/8474179/per-267.patch.log)


1. The node.xml file needs to be updated to reflect the change of the result name from `Space Slug` to `Response Body`.
2. The result `Files` is actually only a single filename, so it would probably make sense to change this to `File` and then update the node.xml file and change the `handle_results` method accordingly.

    ```
      def handle_results(error_msg, filename, response_body)
        <<-RESULTS
        <results>
          <result name="Handler Error Message">#{ERB::Util.html_escape(error_msg)}</result>
          <result name="File">#{ERB::Util.html_escape(filename)}</result>
          <result name="Response Body">#{ERB::Util.html_escape(response_body)}</result>
        </results>
        RESULTS
      end
    ```

3.  The file upload URL query parameters are not escaped. Since these are user inputted values, we must escape them.

    ```
    if destination_token_name.strip.size > 0
      file_upload_url = file_upload_url.include?("?") ?
        "#{file_upload_url}&#{CGI::escape(destination_token_name)}=#{CGI::escape(destination_token_value)}" :
        "#{file_upload_url}?#{CGI::escape(destination_token_name)}=#{CGI::escape(destination_token_value)}"
    end
    ```

4. The `handle_define_multipart_params` method isn't necessary. The `stream_file_upload` method can be modified to take in the mulipart_params hash that was passed as an input parameter, and use it directly. No need to convert to an array of arrays. If that truly is necessary, then simply calling `.to_a` on the hash does the same thing.
5. I see a TODO for handling the `multipart_params` parsing errors, so might as well take care of that now. The `handle_exception` method can be modified to handle the JSON::ParseError case.

    ```
    # Parse the multipart parameter options
    begin
      multipart_params = @parameters["multipart_params"].strip.size > 0 ?
        JSON.parse(@parameters["multipart_params"]) :
        {}
    rescue JSON::ParseError => e
      message = "The multipart params hash parameter is not valid JSON"
      return handle_exception(message, e)
    end
    ```

    ```
    def handle_exception(message, error)
      case error
      when Net::HTTPResponse
        begin
          content = JSON.parse(error.body)
          error_key = content["errorKey"] || error.code
          error_msg = content["error"] || ""
          error_message = "#{message}:\n\tError Key: #{error_key}\n\tError: #{error_msg}"
        rescue StandardError => e
          error_key = error.code
          error_message = "#{message}:\n\tError Key: #{error_key}\n\tError: #{error.body}"
        end
      when NilClass
        error_message = "0: No response from server"
      when JSON::ParseError
        error_message = message
      else
        error_message = "Unexpected error: #{error.inspect}"
      end
      puts error_message
      raise error_message if @raise_error
      handle_results(error_message, nil, nil)
    end
    ```

2022-04-12 16:39 UTC, jackboespflug requested changes
The comments I made earlier need to be addressed.

2022-04-14 15:25 UTC, jackboespflug approved these changes

2022-04-14 15:25 UTC, merged